version: '3.4'

services:
  lttflow.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  lttflow.pgsql:
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=123qwe
            - POSTGRES_DB=lttflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/temp/db:/var/lib/postgresql/data/pgdata